name: Deploy and Publish Extension
on:
  push:
    branches:
      - main
jobs:
  publish_to_vscode_marketplace:
    name: Publish to VSCode Marketplace
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install VSCE
        run: npm install -g vsce
      - name: Install dependencies into node_modules directory for this project
        run: npm install
      - name: Compile extension's source code
        run: npm run compile
      - name: Publish to Visual Studio Code Marketplace
        run: vsce publish -p $VSCE_TOKEN
        env:
          VSCE_TOKEN: ${{ secrets.VS_MARKETPLACE_PAT }}
